name: API Automated Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI Application
      run: |
        uvicorn app.sandbox:app --host 127.0.0.1 --port 8080 &
        sleep 3

    - name: Run Pytest
      env:
        PYTHONPATH: .
      run: |
        pytest --alluredir=allure-results
      continue-on-error: true

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
        retention-days: 1

    - name: Send Telegram Notification
      if: always()  
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_T0 }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🚀 *GitHub Actions Report*
          
          Репозиторий: ${{ github.repository }}
          Событие: ${{ github.event_name }}
          Статус сборки: ${{ job.status == 'success' && '🟢 Успешно' || '🔴 Ошибка' }}
          
          Посмотреть прогон: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}    